//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSearchShortcut.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSearchShortcut.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Arguments (Optional).
        /// </summary>
        internal static string AddShortcutForm_BrowserArgsLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserArgsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser launch arguments, use %1 for URL.
        /// </summary>
        internal static string AddShortcutForm_BrowserArgsPlaceholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserArgsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string AddShortcutForm_BrowserPathDefault {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserPathDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string AddShortcutForm_BrowserPathLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Home Page (Optional).
        /// </summary>
        internal static string AddShortcutForm_HomepageLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_HomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use domain by default.
        /// </summary>
        internal static string AddShortcutForm_HomepagePlaceholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_HomepagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string AddShortcutForm_NameErrorMessage {
            get {
                return ResourceManager.GetString("AddShortcutForm_NameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AddShortcutForm_NameLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Whitespace (Optional).
        /// </summary>
        internal static string AddShortcutForm_ReplaceWhitespaceLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_ReplaceWhitespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which character(s) to replace a space.
        /// </summary>
        internal static string AddShortcutForm_ReplaceWhitespacePlaceholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_ReplaceWhitespacePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddShortcutForm_Save {
            get {
                return ResourceManager.GetString("AddShortcutForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Provider.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProviderLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProviderNone {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProviderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Suggestion Provider.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProviderPlaceholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProviderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        internal static string AddShortcutForm_UrlErrorMessage {
            get {
                return ResourceManager.GetString("AddShortcutForm_UrlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string AddShortcutForm_UrlLabel {
            get {
                return ResourceManager.GetString("AddShortcutForm_UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use %s in the URL for the search term.
        /// </summary>
        internal static string AddShortcutForm_UrlPlaceholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_UrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_AddName {
            get {
                return ResourceManager.GetString("AddShortcutPage_AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_AddTitle {
            get {
                return ResourceManager.GetString("AddShortcutPage_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_EditName {
            get {
                return ResourceManager.GetString("AddShortcutPage_EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_EditTitle {
            get {
                return ResourceManager.GetString("AddShortcutPage_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {engine}.
        /// </summary>
        internal static string OpenHomePageCommand_Name {
            get {
                return ResourceManager.GetString("OpenHomePageCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {engine}.
        /// </summary>
        internal static string SearchPage_MoreCommandsName {
            get {
                return ResourceManager.GetString("SearchPage_MoreCommandsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {engine}.
        /// </summary>
        internal static string SearchPage_MoreCommandsTitle {
            get {
                return ResourceManager.GetString("SearchPage_MoreCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {engine} for &quot;{query}&quot;.
        /// </summary>
        internal static string SearchPage_Subtitle {
            get {
                return ResourceManager.GetString("SearchPage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for &quot;{query}&quot;.
        /// </summary>
        internal static string SearchWebCommand_Name {
            get {
                return ResourceManager.GetString("SearchWebCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {engine} for &quot;{query}&quot;.
        /// </summary>
        internal static string SuggestionsProvider_Description {
            get {
                return ResourceManager.GetString("SuggestionsProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WebSearchShortcutCommandsProvider_CommandItemDeleteName {
            get {
                return ResourceManager.GetString("WebSearchShortcutCommandsProvider_CommandItemDeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WebSearchShortcutCommandsProvider_CommandItemDeleteTitle {
            get {
                return ResourceManager.GetString("WebSearchShortcutCommandsProvider_CommandItemDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {engine}.
        /// </summary>
        internal static string WebSearchShortcutCommandsProvider_CommandItemSubtitle {
            get {
                return ResourceManager.GetString("WebSearchShortcutCommandsProvider_CommandItemSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSearchShortcut.
        /// </summary>
        internal static string WebSearchShortcutCommandsProvider_DisplayName {
            get {
                return ResourceManager.GetString("WebSearchShortcutCommandsProvider_DisplayName", resourceCulture);
            }
        }
    }
}
