//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSearchShortcut.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSearchShortcut.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Arguments (Optional).
        /// </summary>
        internal static string AddShortcutForm_BrowserArgs_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserArgs_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser launch arguments, use %1 for URL.
        /// </summary>
        internal static string AddShortcutForm_BrowserArgs_Placeholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserArgs_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string AddShortcutForm_BrowserPath_Default {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserPath_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string AddShortcutForm_BrowserPath_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_BrowserPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Home Page (Optional).
        /// </summary>
        internal static string AddShortcutForm_Homepage_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_Homepage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use domain by default.
        /// </summary>
        internal static string AddShortcutForm_Homepage_Placeholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_Homepage_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string AddShortcutForm_Name_ErrorMessage {
            get {
                return ResourceManager.GetString("AddShortcutForm_Name_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AddShortcutForm_Name_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        internal static string AddShortcutForm_RecordHistory_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_RecordHistory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record history for this shortcut.
        /// </summary>
        internal static string AddShortcutForm_RecordHistory_Title {
            get {
                return ResourceManager.GetString("AddShortcutForm_RecordHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Whitespace (Optional).
        /// </summary>
        internal static string AddShortcutForm_ReplaceWhitespace_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_ReplaceWhitespace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which character(s) to replace a space.
        /// </summary>
        internal static string AddShortcutForm_ReplaceWhitespace_Placeholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_ReplaceWhitespace_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddShortcutForm_Save {
            get {
                return ResourceManager.GetString("AddShortcutForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Provider.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProvider_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProvider_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProvider_None {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProvider_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Suggestion Provider.
        /// </summary>
        internal static string AddShortcutForm_SuggestionProvider_Placeholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_SuggestionProvider_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        internal static string AddShortcutForm_Url_ErrorMessage {
            get {
                return ResourceManager.GetString("AddShortcutForm_Url_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string AddShortcutForm_Url_Label {
            get {
                return ResourceManager.GetString("AddShortcutForm_Url_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use %s in the URL for the search term.
        /// </summary>
        internal static string AddShortcutForm_Url_Placeholder {
            get {
                return ResourceManager.GetString("AddShortcutForm_Url_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Shortcut.
        /// </summary>
        internal static string AddShortcutItem_Name {
            get {
                return ResourceManager.GetString("AddShortcutItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Shortcut.
        /// </summary>
        internal static string AddShortcutItem_Title {
            get {
                return ResourceManager.GetString("AddShortcutItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_Title_Add {
            get {
                return ResourceManager.GetString("AddShortcutPage_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Search Shortcut.
        /// </summary>
        internal static string AddShortcutPage_Title_Edit {
            get {
                return ResourceManager.GetString("AddShortcutPage_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear {shortcut}&apos;s History.
        /// </summary>
        internal static string ClearHistory_TitleTemplate {
            get {
                return ResourceManager.GetString("ClearHistory_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHistory_TitleTemplate {
            get {
                return ResourceManager.GetString("DeleteHistory_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteShortcutItem_TitleTemplate {
            get {
                return ResourceManager.GetString("DeleteShortcutItem_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Search Shortcut.
        /// </summary>
        internal static string EditShortcutItem_NameTemplate {
            get {
                return ResourceManager.GetString("EditShortcutItem_NameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Search Shortcut.
        /// </summary>
        internal static string EditShortcutItem_TitleTemplate {
            get {
                return ResourceManager.GetString("EditShortcutItem_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {shortcut}.
        /// </summary>
        internal static string OpenHomepageItem_NameTemplate {
            get {
                return ResourceManager.GetString("OpenHomepageItem_NameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {shortcut}.
        /// </summary>
        internal static string OpenHomepageItem_TitleTemplate {
            get {
                return ResourceManager.GetString("OpenHomepageItem_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for &quot;{query}&quot;.
        /// </summary>
        internal static string SearchQueryItem_NameTemplate {
            get {
                return ResourceManager.GetString("SearchQueryItem_NameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {shortcut} for &quot;{query}&quot;.
        /// </summary>
        internal static string SearchQueryItem_SubtitleTemplate {
            get {
                return ResourceManager.GetString("SearchQueryItem_SubtitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {query}.
        /// </summary>
        internal static string SearchQueryItem_TitleTemplate {
            get {
                return ResourceManager.GetString("SearchQueryItem_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {shortcut}.
        /// </summary>
        internal static string SearchWebPage_TitleTemplate {
            get {
                return ResourceManager.GetString("SearchWebPage_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum total items shown per search.
        /// </summary>
        internal static string Settings_MaxDisplayCount_Description {
            get {
                return ResourceManager.GetString("Settings_MaxDisplayCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer greater than or equal to 1.
        /// </summary>
        internal static string Settings_MaxDisplayCount_ErrorMessage {
            get {
                return ResourceManager.GetString("Settings_MaxDisplayCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Search Results.
        /// </summary>
        internal static string Settings_MaxDisplayCount_Label {
            get {
                return ResourceManager.GetString("Settings_MaxDisplayCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of history results shown during search; set to 0 to hide history. Any value exceeding “Max Search Results” is ignored..
        /// </summary>
        internal static string Settings_MaxHistoryDisplayCount_Description {
            get {
                return ResourceManager.GetString("Settings_MaxHistoryDisplayCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer greater than or equal to 0.
        /// </summary>
        internal static string Settings_MaxHistoryDisplayCount_ErrorMessage {
            get {
                return ResourceManager.GetString("Settings_MaxHistoryDisplayCount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max History Results.
        /// </summary>
        internal static string Settings_MaxHistoryDisplayCount_Label {
            get {
                return ResourceManager.GetString("Settings_MaxHistoryDisplayCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {shortcut}.
        /// </summary>
        internal static string ShortcutItem_NameTemplate {
            get {
                return ResourceManager.GetString("ShortcutItem_NameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search {shortcut}.
        /// </summary>
        internal static string ShortcutItem_SubtitleTemplate {
            get {
                return ResourceManager.GetString("ShortcutItem_SubtitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {shortcut}.
        /// </summary>
        internal static string ShortcutItem_TitleTemplate {
            get {
                return ResourceManager.GetString("ShortcutItem_TitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSearchShortcut.
        /// </summary>
        internal static string WebSearchShortcut_DisplayName {
            get {
                return ResourceManager.GetString("WebSearchShortcut_DisplayName", resourceCulture);
            }
        }
    }
}
